// Decompiled with JetBrains decompiler
// Type: IronPython.Modules.PythonErrorNumber
// Assembly: IronPython.Modules, Version=2.7.9.0, Culture=neutral, PublicKeyToken=7f709c5b713576e1
// MVID: 7E74D536-11C2-4DF1-B811-06D30EAF7D30
// Assembly location: C:\Users\futiliter\Documents\Projects\OpenBullet\OpenBullet-ReverseEngineered\libs\IronPython.Modules.dll

using IronPython.Runtime;
using System.Runtime.CompilerServices;

#nullable disable
namespace IronPython.Modules;

public static class PythonErrorNumber
{
  public const string __doc__ = "Provides a list of common error numbers.  These numbers are frequently reported in various exceptions.";
  public const int E2BIG = 7;
  public const int EACCES = 13;
  public const int EADDRINUSE = 10048;
  public const int EADDRNOTAVAIL = 10049;
  public const int EAFNOSUPPORT = 10047;
  public const int EAGAIN = 11;
  public const int EALREADY = 10037;
  public const int EBADF = 9;
  public const int EBUSY = 16 /*0x10*/;
  public const int ECHILD = 10;
  public const int ECONNABORTED = 10053;
  public const int ECONNREFUSED = 10061;
  public const int ECONNRESET = 10054;
  public const int EDEADLK = 36;
  public const int EDEADLOCK = 36;
  public const int EDESTADDRREQ = 10039;
  public const int EDOM = 33;
  public const int EDQUOT = 10069;
  public const int EEXIST = 17;
  public const int EFAULT = 14;
  public const int EFBIG = 27;
  public const int EHOSTDOWN = 10064;
  public const int EHOSTUNREACH = 10065;
  public const int EILSEQ = 42;
  public const int EINPROGRESS = 10036;
  public const int EINTR = 4;
  public const int EINVAL = 22;
  public const int EIO = 5;
  public const int EISCONN = 10056;
  public const int EISDIR = 21;
  public const int ELOOP = 10062;
  public const int EMFILE = 24;
  public const int EMLINK = 31 /*0x1F*/;
  public const int EMSGSIZE = 10040;
  public const int ENAMETOOLONG = 38;
  public const int ENETDOWN = 10050;
  public const int ENETRESET = 10052;
  public const int ENETUNREACH = 10051;
  public const int ENFILE = 23;
  public const int ENOBUFS = 10055;
  public const int ENODEV = 19;
  public const int ENOENT = 2;
  public const int ENOEXEC = 8;
  public const int ENOLCK = 39;
  public const int ENOMEM = 12;
  public const int ENOPROTOOPT = 10042;
  public const int ENOSPC = 28;
  public const int ENOSYS = 40;
  public const int ENOTCONN = 10057;
  public const int ENOTDIR = 20;
  public const int ENOTEMPTY = 41;
  public const int ENOTSOCK = 10038;
  public const int ENOTTY = 25;
  public const int ENXIO = 6;
  public const int EOPNOTSUPP = 10045;
  public const int EPERM = 1;
  public const int EPFNOSUPPORT = 10046;
  public const int EPIPE = 32 /*0x20*/;
  public const int EPROTONOSUPPORT = 10043;
  public const int EPROTOTYPE = 10041;
  public const int ERANGE = 34;
  public const int EREMOTE = 10071;
  public const int EROFS = 30;
  public const int ESHUTDOWN = 10058;
  public const int ESOCKTNOSUPPORT = 10044;
  public const int ESPIPE = 29;
  public const int ESRCH = 3;
  public const int ESTALE = 10070;
  public const int ETIMEDOUT = 10060;
  public const int ETOOMANYREFS = 10059;
  public const int EUSERS = 10068;
  public const int EWOULDBLOCK = 10035;
  public const int EXDEV = 18;
  public const int WSABASEERR = 10000;
  public const int WSAEACCES = 10013;
  public const int WSAEADDRINUSE = 10048;
  public const int WSAEADDRNOTAVAIL = 10049;
  public const int WSAEAFNOSUPPORT = 10047;
  public const int WSAEALREADY = 10037;
  public const int WSAEBADF = 10009;
  public const int WSAECONNABORTED = 10053;
  public const int WSAECONNREFUSED = 10061;
  public const int WSAECONNRESET = 10054;
  public const int WSAEDESTADDRREQ = 10039;
  public const int WSAEDISCON = 10101;
  public const int WSAEDQUOT = 10069;
  public const int WSAEFAULT = 10014;
  public const int WSAEHOSTDOWN = 10064;
  public const int WSAEHOSTUNREACH = 10065;
  public const int WSAEINPROGRESS = 10036;
  public const int WSAEINTR = 10004;
  public const int WSAEINVAL = 10022;
  public const int WSAEISCONN = 10056;
  public const int WSAELOOP = 10062;
  public const int WSAEMFILE = 10024;
  public const int WSAEMSGSIZE = 10040;
  public const int WSAENAMETOOLONG = 10063;
  public const int WSAENETDOWN = 10050;
  public const int WSAENETRESET = 10052;
  public const int WSAENETUNREACH = 10051;
  public const int WSAENOBUFS = 10055;
  public const int WSAENOPROTOOPT = 10042;
  public const int WSAENOTCONN = 10057;
  public const int WSAENOTEMPTY = 10066;
  public const int WSAENOTSOCK = 10038;
  public const int WSAEOPNOTSUPP = 10045;
  public const int WSAEPFNOSUPPORT = 10046;
  public const int WSAEPROCLIM = 10067;
  public const int WSAEPROTONOSUPPORT = 10043;
  public const int WSAEPROTOTYPE = 10041;
  public const int WSAEREMOTE = 10071;
  public const int WSAESHUTDOWN = 10058;
  public const int WSAESOCKTNOSUPPORT = 10044;
  public const int WSAESTALE = 10070;
  public const int WSAETIMEDOUT = 10060;
  public const int WSAETOOMANYREFS = 10059;
  public const int WSAEUSERS = 10068;
  public const int WSAEWOULDBLOCK = 10035;
  public const int WSANOTINITIALISED = 10093;
  public const int WSASYSNOTREADY = 10091;
  public const int WSAVERNOTSUPPORTED = 10092;

  [SpecialName]
  public static void PerformModuleReload(PythonContext context, PythonDictionary dict)
  {
    dict[(object) "errorcode"] = (object) new PythonDictionary()
    {
      [(object) 7] = (object) "E2BIG",
      [(object) 13] = (object) "EACCES",
      [(object) 10048] = (object) "EADDRINUSE",
      [(object) 10049] = (object) "EADDRNOTAVAIL",
      [(object) 10047] = (object) "EAFNOSUPPORT",
      [(object) 11] = (object) "EAGAIN",
      [(object) 10037] = (object) "EALREADY",
      [(object) 9] = (object) "EBADF",
      [(object) 16 /*0x10*/] = (object) "EBUSY",
      [(object) 10] = (object) "ECHILD",
      [(object) 10053] = (object) "ECONNABORTED",
      [(object) 10061] = (object) "ECONNREFUSED",
      [(object) 10054] = (object) "ECONNRESET",
      [(object) 36] = (object) "EDEADLK",
      [(object) 36] = (object) "EDEADLOCK",
      [(object) 10039] = (object) "EDESTADDRREQ",
      [(object) 33] = (object) "EDOM",
      [(object) 10069] = (object) "EDQUOT",
      [(object) 17] = (object) "EEXIST",
      [(object) 14] = (object) "EFAULT",
      [(object) 27] = (object) "EFBIG",
      [(object) 10064] = (object) "EHOSTDOWN",
      [(object) 10065] = (object) "EHOSTUNREACH",
      [(object) 42] = (object) "EILSEQ",
      [(object) 10036] = (object) "EINPROGRESS",
      [(object) 4] = (object) "EINTR",
      [(object) 22] = (object) "EINVAL",
      [(object) 5] = (object) "EIO",
      [(object) 10056] = (object) "EISCONN",
      [(object) 21] = (object) "EISDIR",
      [(object) 10062] = (object) "ELOOP",
      [(object) 24] = (object) "EMFILE",
      [(object) 31 /*0x1F*/] = (object) "EMLINK",
      [(object) 10040] = (object) "EMSGSIZE",
      [(object) 38] = (object) "ENAMETOOLONG",
      [(object) 10050] = (object) "ENETDOWN",
      [(object) 10052] = (object) "ENETRESET",
      [(object) 10051] = (object) "ENETUNREACH",
      [(object) 23] = (object) "ENFILE",
      [(object) 10055] = (object) "ENOBUFS",
      [(object) 19] = (object) "ENODEV",
      [(object) 2] = (object) "ENOENT",
      [(object) 8] = (object) "ENOEXEC",
      [(object) 39] = (object) "ENOLCK",
      [(object) 12] = (object) "ENOMEM",
      [(object) 10042] = (object) "ENOPROTOOPT",
      [(object) 28] = (object) "ENOSPC",
      [(object) 40] = (object) "ENOSYS",
      [(object) 10057] = (object) "ENOTCONN",
      [(object) 20] = (object) "ENOTDIR",
      [(object) 41] = (object) "ENOTEMPTY",
      [(object) 10038] = (object) "ENOTSOCK",
      [(object) 25] = (object) "ENOTTY",
      [(object) 6] = (object) "ENXIO",
      [(object) 10045] = (object) "EOPNOTSUPP",
      [(object) 1] = (object) "EPERM",
      [(object) 10046] = (object) "EPFNOSUPPORT",
      [(object) 32 /*0x20*/] = (object) "EPIPE",
      [(object) 10043] = (object) "EPROTONOSUPPORT",
      [(object) 10041] = (object) "EPROTOTYPE",
      [(object) 34] = (object) "ERANGE",
      [(object) 10071] = (object) "EREMOTE",
      [(object) 30] = (object) "EROFS",
      [(object) 10058] = (object) "ESHUTDOWN",
      [(object) 10044] = (object) "ESOCKTNOSUPPORT",
      [(object) 29] = (object) "ESPIPE",
      [(object) 3] = (object) "ESRCH",
      [(object) 10070] = (object) "ESTALE",
      [(object) 10060] = (object) "ETIMEDOUT",
      [(object) 10059] = (object) "ETOOMANYREFS",
      [(object) 10068] = (object) "EUSERS",
      [(object) 10035] = (object) "EWOULDBLOCK",
      [(object) 18] = (object) "EXDEV",
      [(object) 10000] = (object) "WSABASEERR",
      [(object) 10013] = (object) "WSAEACCES",
      [(object) 10048] = (object) "WSAEADDRINUSE",
      [(object) 10049] = (object) "WSAEADDRNOTAVAIL",
      [(object) 10047] = (object) "WSAEAFNOSUPPORT",
      [(object) 10037] = (object) "WSAEALREADY",
      [(object) 10009] = (object) "WSAEBADF",
      [(object) 10053] = (object) "WSAECONNABORTED",
      [(object) 10061] = (object) "WSAECONNREFUSED",
      [(object) 10054] = (object) "WSAECONNRESET",
      [(object) 10039] = (object) "WSAEDESTADDRREQ",
      [(object) 10101] = (object) "WSAEDISCON",
      [(object) 10069] = (object) "WSAEDQUOT",
      [(object) 10014] = (object) "WSAEFAULT",
      [(object) 10064] = (object) "WSAEHOSTDOWN",
      [(object) 10065] = (object) "WSAEHOSTUNREACH",
      [(object) 10036] = (object) "WSAEINPROGRESS",
      [(object) 10004] = (object) "WSAEINTR",
      [(object) 10022] = (object) "WSAEINVAL",
      [(object) 10056] = (object) "WSAEISCONN",
      [(object) 10062] = (object) "WSAELOOP",
      [(object) 10024] = (object) "WSAEMFILE",
      [(object) 10040] = (object) "WSAEMSGSIZE",
      [(object) 10063] = (object) "WSAENAMETOOLONG",
      [(object) 10050] = (object) "WSAENETDOWN",
      [(object) 10052] = (object) "WSAENETRESET",
      [(object) 10051] = (object) "WSAENETUNREACH",
      [(object) 10055] = (object) "WSAENOBUFS",
      [(object) 10042] = (object) "WSAENOPROTOOPT",
      [(object) 10057] = (object) "WSAENOTCONN",
      [(object) 10066] = (object) "WSAENOTEMPTY",
      [(object) 10038] = (object) "WSAENOTSOCK",
      [(object) 10045] = (object) "WSAEOPNOTSUPP",
      [(object) 10046] = (object) "WSAEPFNOSUPPORT",
      [(object) 10067] = (object) "WSAEPROCLIM",
      [(object) 10043] = (object) "WSAEPROTONOSUPPORT",
      [(object) 10041] = (object) "WSAEPROTOTYPE",
      [(object) 10071] = (object) "WSAEREMOTE",
      [(object) 10058] = (object) "WSAESHUTDOWN",
      [(object) 10044] = (object) "WSAESOCKTNOSUPPORT",
      [(object) 10070] = (object) "WSAESTALE",
      [(object) 10060] = (object) "WSAETIMEDOUT",
      [(object) 10059] = (object) "WSAETOOMANYREFS",
      [(object) 10068] = (object) "WSAEUSERS",
      [(object) 10035] = (object) "WSAEWOULDBLOCK",
      [(object) 10093] = (object) "WSANOTINITIALISED",
      [(object) 10091] = (object) "WSASYSNOTREADY",
      [(object) 10092] = (object) "WSAVERNOTSUPPORTED"
    };
  }
}
